@echo off
AMIDEWINx64.exe /IVN SHADOWZIN--%random%-%random%-Spoofer
AMIDEWINx64.exe /IV  SHADOWZIN--%random%-%random%-Spoofer
AMIDEWINx64.exe /ID  SHADOWZIN--%random%-%random%-Spoofer
AMIDEWINx64.exe /SM  SHADOWZIN--%random%-%random%-Spoofer
AMIDEWINx64.exe /SP  SHADOWZIN--%random%-%random%-Spoofer
AMIDEWINx64.exe /SV  SHADOWZIN--%random%-%random%-Spoofer
AMIDEWINx64.exe /SS  SHADOWZIN--%random%-%random%-Spoofer
AMIDEWINx64.exe /SU  SHADOWZIN--%random%-%random%-Spoofer
AMIDEWINx64.exe /SK  SHADOWZIN--%random%-%random%-Spoofer
AMIDEWINx64.exe /SF  SHADOWZIN--%random%-%random%-Spoofer
AMIDEWINx64.exe /BM  SHADOWZIN--%random%-%random%-Spoofer
AMIDEWINx64.exe /BP  SHADOWZIN--%random%-%random%-Spoofer
AMIDEWINx64.exe /BV  SHADOWZIN--%random%-%random%-Spoofer
AMIDEWINx64.exe /BS  SHADOWZIN--%random%-%random%-Spoofer
AMIDEWINx64.exe /BT  SHADOWZIN--%random%-%random%-Spoofer
AMIDEWINx64.exe /BLC SHADOWZIN--%random%-%random%-Spoofer
AMIDEWINx64.exe /CM  SHADOWZIN--%random%-%random%-Spoofer
AMIDEWINx64.exe /CT  SHADOWZIN--%random%-%random%-Spoofer
AMIDEWINx64.exe /CA  SHADOWZIN--%random%-%random%-Spoofer
AMIDEWINx64.exe /CS  SHADOWZIN--%random%-%random%-Spoofer
AMIDEWINx64.exe /CV  SHADOWZIN--%random%-%random%-Spoofer
AMIDEWINx64.exe /CO  SHADOWZIN--%random%-%random%-Spoofer
AMIDEWINx64.exe /CPC SHADOWZIN--%random%-%random%-Spoofer
AMIDEWINx64.exe /CSK SHADOWZIN--%random%-%random%-Spoofer
AMIDEWINx64.exe /CH  SHADOWZIN--%random%-%random%-Spoofer
AMIDEWINx64.exe /PSN SHADOWZIN--%random%-%random%-Spoofer
AMIDEWINx64.exe /PAT SHADOWZIN--%random%-%random%-Spoofer
AMIDEWINx64.exe /PPN SHADOWZIN--%random%-%random%-Spoofer